fix message generation
current main branch doesn't build, this error occurs:

/home/nick/catkin_ws/src/LiDAR_IMU_Init/src/IMU_Processing.hpp:27:10: fatal error: lidar_imu_init/States.h: No such file or directory
\#include <lidar_imu_init/States.h>

This is because of the order at which message generation is caled in the CMakeLists.txt
Message generation must be called before we include these files which require the message types

Tested this on ubuntu20 and it builds fine now